FROM mongo:latest

# PREPARE LINUX PROGRAMMS
RUN apt-get update
RUN apt-get install -y mc
RUN apt-get install -y htop
RUN apt-get install -y curl
RUN apt-get install -y language-pack-ru
RUN apt-get install -y language-pack-en
